# Generated by Django 6.0.3 on 2026-04-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='hash',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tx_id',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
