# Generated by Django 6.0.3 on 2026-04-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='app_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
